const nav=document.getElementById('nav');
addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>24),{passive:true});
const burger=document.getElementById('burger'),mm=document.getElementById('mmenu');
burger.addEventListener('click',()=>{const o=mm.classList.toggle('open');burger.textContent=o?'✕':'☰';burger.setAttribute('aria-expanded',o)});
mm.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mm.classList.remove('open');burger.textContent='☰'}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.rv,.step').forEach(el=>{el.classList.add('rv');io.observe(el)});
document.querySelectorAll('.step').forEach(s=>new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){s.classList.add('visible');o.disconnect()}}),{threshold:.4}).observe(s));
// active nav
const secs=[...document.querySelectorAll('section[id]')];
const links=[...document.querySelectorAll('.links a')];
new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-40% 0px -55% 0px'}).observe && secs.forEach(s=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle('active',l.hash==='#'+s.id))}),{rootMargin:'-40% 0px -55% 0px'}).observe(s));
// Case study modal data
const CASES={
lead:{cat:'Automation / AI Agents',title:'AI Lead Generation Engine',sub:'From prospect discovery to sales-ready intelligence.',challenge:' prospect data is scattered, research is manual, and outreach lists lack structure. Teams spend hours qualifying leads that never convert.',system:'A staged automation architecture: discover → research → enrich → analyze → qualify → activate. Each stage structures data before passing it downstream.',steps:['Discover prospect sources and collect raw business data','Research and enrich with firmographic signals','AI analysis: fit, intent and quality scoring','Qualification gate with structured output','Activation: push sales-ready records to outreach / CRM'],intel:'LLM classification over enriched fields — industry, size signals, contact quality — producing a consistent qualification schema instead of gut-feel lists.',integ:['n8n','OpenAI / LLMs','Google Sheets / Database','Webhooks → CRM / outreach'],outcome:'A repeatable pipeline. No invented volumes claimed — value is measured in hours saved and consistency of qualification.',lesson:'Structure the data first; AI judgement is only reliable on clean inputs.'},
support:{cat:'Conversational AI / Ops',title:'AI Customer Operations',sub:'Intelligent support with human escalation.',challenge:'Support inboxes mix orders, subscriptions and general questions. Manual triage is slow and inconsistent.',system:'Automated intake → ticket normalization → AI analysis/classification → business-data lookup → decision logic → auto-resolve or human review.',steps:['Customer message intake (chat / email)','Normalize into a standard ticket object','AI classifies intent + urgency','Lookup order / subscription context','Decision: auto-resolve with grounded answer OR route to human with full context'],intel:'The key rule: automation should know when to act — and when to involve a human. Confidence thresholds and policy checks gate every auto-response.',integ:['n8n','LLMs + knowledge base','Shopify / order systems','Email / messaging'],outcome:'Faster first response, consistent triage, and humans only where judgement is needed.',lesson:'Escalation design is the product — not an afterthought.'},
agents:{cat:'Multi-Agent Systems',title:'Multi-Agent Business System',sub:'One intelligent layer. Multiple specialist systems.',challenge:'One giant prompt/agent forced to do everything becomes fragile. Routing, tools and context collide.',system:'Master agent → intent routing → specialist agents → execution → unified result. Specialists own narrow tools and schemas.',steps:['Master agent receives request + context','Router classifies task type','Specialist agent executes with scoped tools','Results validated and merged','Final response + logged actions'],intel:'Routing + scoped memory. Each specialist sees only what it needs, keeping reasoning sharp and auditable.',integ:['n8n / orchestration','OpenAI agents','APIs + webhooks','Supabase / Sheets'],outcome:'Modular, debuggable automation that can grow by adding specialists — not rewriting everything.',lesson:'Decompose before you automate.'},
voice:{cat:'Voice AI',title:'AI Voice Receptionist',sub:'Conversations that connect to business operations.',challenge:'Missed calls mean missed revenue. Hiring full-time cover for every call is expensive for small businesses.',system:'Call → conversation → understand → decide → book / update / escalate → business system.',steps:['Inbound call answered instantly','Natural conversation + info capture','Extract structured intent (booking, query, urgency)','Trigger workflow: calendar / CRM / ticket','Escalate to human when needed with transcript'],intel:'Speech-to-text → LLM reasoning over business knowledge → structured extraction → tool calls. Development/tested flows; production scope confirmed per client.',integ:['Twilio / Voice','Conversational AI','Google Calendar / Workspace','CRM + notifications'],outcome:'No missed first contact; every call becomes structured data. Deployment claims kept honest to tested scope.',lesson:'Voice AI succeeds on extraction accuracy, not chattiness.'},
ecom:{cat:'E-commerce',title:'E-commerce Growth Automation',sub:'Connecting customer data, campaigns and operations.',challenge:'Stores collect orders but fail to segment, follow up, and recover revenue systematically.',system:'Store → customer data → segmentation → AI / campaign logic → communication → follow-up.',steps:['Sync orders + customer events','Segment by behavior and value','Generate campaign logic / content angles','Send email / messaging flows','Post-purchase + win-back follow-up'],integ:['Shopify','Stripe','Email / messaging','Sheets / CRM'],intel:'Segmentation plus AI-assisted messaging keeps campaigns relevant without manual list-pulling.',outcome:'A connected loop from purchase to repeat purchase — scoped to integrations actually implemented.',lesson:'Retention is a system, not a blast.'},
content:{cat:'Media Automation',title:'AI Content Production System',sub:'From idea to publishable media.',challenge:'Consistent content requires scripting, voice, visuals, editing and distribution — too many steps to sustain manually.',system:'Idea → script → voice → visuals → video → distribution.',steps:['Idea + brief capture','AI script draft + human polish','Voice generation','Visual / video assembly','Review gate','Scheduled distribution'],integ:['LLMs','Voice generation','AI video + editing','Social schedulers'],intel:'Human-in-the-loop review gates keep quality high; automation handles assembly and formatting.',outcome:'Faster throughput without pretending to be a full media house. Scale stated honestly.',lesson:'Automate the pipeline, keep taste human.'}};
const modal=document.getElementById('modal'),mbox=document.getElementById('mbox');
function openCase(k){const c=CASES[k];if(!c)return;
mbox.innerHTML=`<button class="closebtn" id="mclose" aria-label="Close">✕</button>
<p class="label">${c.cat}</p><h3>${c.title}</h3><p class="sub" style="font-family:var(--font-m);font-size:12px;letter-spacing:.14em;color:var(--silver);text-transform:uppercase">${c.sub}</p>
<div class="case-sec"><b>THE CHALLENGE</b><p style="color:var(--muted)">${c.challenge}</p></div>
<div class="case-sec"><b>THE SYSTEM</b><p style="color:var(--muted)">${c.system}</p></div>
<div class="case-sec"><b>HOW IT WORKS</b><ol style="color:var(--muted)">${(c.steps||[]).map(s=>`<li>${s}</li>`).join('')}</ol></div>
<div class="case-sec"><b>INTELLIGENCE LAYER</b><p style="color:var(--muted)">${c.intel}</p></div>
<div class="case-sec"><b>INTEGRATIONS</b><p>${(c.integ||[]).map(t=>`<span class="mini-tags"><span style="font-family:var(--font-m);font-size:11px;border:1px solid var(--line2);border-radius:999px;padding:6px 11px;margin:0 6px 6px 0;display:inline-block">${t}</span></span>`).join('')}</p></div>
<div class="case-sec"><b>OUTCOME</b><p style="color:var(--muted)">${c.outcome}</p></div>
<div class="case-sec"><b>LESSON</b><p style="color:var(--muted)">${c.lesson}</p></div>
<div style="margin-top:24px;display:flex;gap:10px;flex-wrap:wrap"><a class="btn solid" href="#contact">Have a similar problem? Start a project ↗</a></div>`;
modal.classList.add('open');document.body.style.overflow='hidden';
document.getElementById('mclose').onclick=closeCase;
mbox.querySelector('a[href="#contact"]').addEventListener('click',closeCase);
history.replaceState(null,'','#/work/'+k);}
function closeCase(){modal.classList.remove('open');document.body.style.overflow='';history.replaceState(null,'',' ')}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.case)));
modal.querySelector('.modal-bg').addEventListener('click',closeCase);
addEventListener('keydown',e=>{if(e.key==='Escape')closeCase()});
if(location.hash.startsWith('#/work/'))openCase(location.hash.split('/')[2]);
// form: frontend only, clear integration point
const form=document.getElementById('inquiry'),note=document.getElementById('formnote');
form.addEventListener('submit',e=>{e.preventDefault();
const d=Object.fromEntries(new FormData(form).entries());
// INTEGRATION POINT: POST `d` to /api/contact or Formspree/Webhook, or send to adebayoemmanuelibk@gmail.com
note.innerHTML=`Thanks ${d.name?('<b>'+d.name.split(' ')[0]+'</b> — '):''}your brief is ready. <br><span style="color:var(--muted)">To activate delivery, connect this form to your endpoint (see <code>app.js → INTEGRATION POINT</code>), or email directly: <a style="color:var(--lime)" href="mailto:adebayoemmanuelibk@gmail.com?subject=${encodeURIComponent('Project inquiry — '+(d.company||d.name||''))}&body=${encodeURIComponent(JSON.stringify(d,null,2))}">adebayoemmanuelibk@gmail.com</a>.</span>`;
note.style.borderColor='rgba(199,255,61,.5)';form.reset();
console.log('INQUIRY (wire to backend):',d);});
document.getElementById('yr').textContent=new Date().getFullYear();
